### ISSUE TITLE
Dont work -N switch

### ISSUE THREAD

**Issue by Quake4** [graemes/poolparty-x16r#2]
Please remove hardcode. But retain your default value.

**Comment by graemes** [comment]
The miner has been modified so that if you use "-b 0" it will simply use a rolling hashrate calculated over the entire system run i.e. will not collect transaction samples.  If for some reason you want the hash rate to be calculated based on "-N" number of samples when "-b 0" then use "--no-simple-hr".  In all other case I tightened up the checks so that the miner will work in the same way it always has (which will be in the next release).

**Comment by Quake4** [comment]
I use -N switch on other miners to compare total average hashrate. I add --no-simple-hr and all works fine. Thanks.
